### ISSUE TITLE
Question: Dynamic content possible

### ISSUE THREAD

**Issue by tolotos-rgu** [jonataswalker/ol3-contextmenu#1]
Hi, 
is it possible to add dynamic content to the context menu? 
I want to add menu item based on vector features below the mouse. 
-- Tolotos

**Comment by jonataswalker** [comment]
Hi @tolotos-rgu, not yet, sorry the lack of docs.
I'll try (in the next hours) to add a method for this.

**Comment by jonataswalker** [comment]
@tolotos-rgu please, take a look at the new released version, and updated [README](https://github.com/jonataswalker/ol3-contextmenu/blob/master/README.md).

**Comment by tolotos-rgu** [comment]
Thank you for the quick change. 
I did the following now:

```javascript
var contextmenu = new ContextMenu();
map.addControl(contextmenu);
map.getViewport().addEventListener('contextmenu', buildContextMenu);

function buildContextMenu(evt) {
  // do some stuff to the the features below the mouse and build the menu array.
  // test sample
  var contextMenuEntries = [{
	text: 'Item 1',
	// icon: 'images/item1.png',
	callback: function () { alert('please implement print function') }
  }];
  contextmenu.clear();
  contextmenu.extend(contextMenuEntries);
}
```

Is this code correct? 
The context menu is displayed but i can't click on an entry?!

Two further points to ask for:
1) Is it possible to add support for sub menu item like:
```javascript
var contextMenuEntries = [{
	text: 'Item 1',
	// icon: 'images/item1.png',
	subItems: [{
            text: 'SubItem 1',
	    // icon: 'images/item1.png',
           callback: ....
        }]
  }];
```
2) Is it possible to add a 'disable' attribute to the items?
```javascript
{
    text: 'Item 1',
    // icon: 'images/item1.png',
    disable: true, // default is false
    [callback|subItems]: ...
}
```
I want to have the following function behind: A menu item can have 3 states 
```javascript
[EXECUTABLE, NOT_EXECUTABLE, NEVER_EXECUTABLE]
```
* The EXECUTABLE will be displayed normal
* The NOT_EXECUTABLE will be displayed gray and can not be clicked
* The NEVER_EXECUTABLE will not be added to the context menu

-- Tolotos

**Comment by tolotos-rgu** [comment]
I run into an error:
```javascript 
var contextmenu = new ContextMenu({	default_items: false });
map.addControl(contextmenu);
```
causes:
```javascript 
Uncaught TypeError: Failed to execute 'appendChild' on 'Node': parameter 1 is not of type 'Node'.
os.js:115
```

**Comment by jonataswalker** [comment]
@tolotos-rgu I'm running to catch these errors.

**Comment by jonataswalker** [comment]
@tolotos-rgu Could you check if this is fixed against new released version? I mean the errors.

**Comment by jonataswalker** [comment]
> Is it possible to add support for sub menu item like:

It requires a bit of work. For sure it would a great to have submenus.

> Is it possible to add a 'disable' attribute to the items?

Not yet, I'll have to add some more control on item indexes, I guess you'll want to enable the item under certain circumstances.

About your code, there's no need for:
```javascript
map.getViewport().addEventListener('contextmenu', buildContextMenu);
```
The listener was already added to viewport. Just call your `buildContextMenu` when is needed.

**Comment by tolotos-rgu** [comment]
Wow your fast as light ;-) - Thank you very much!
The fix work i can select the menu items and the callback is called. 

The contextmenu event listener is needed to build the context menu entries at the time of the right click. I can only call the under laying system if a function is callable - the response are the 3 states above. Maybe you can add a addListener(buildContenxmenuFunction) to your interface? 

Is it possible to get access to the default menu items so i can add they again after calling clean() ?
Like getDefaultEntries({ return [zoomIn, zoomOut] }); 

The implementation of the subItems, disable-attribute and access to the default entries would be nice and I can wait for it some time. If say they will come during next year I'm happy. 

-- Tolotos

**Comment by tolotos-rgu** [comment]
On new issue with the new version 1.0.1. 
I'm running openlayers in a JavaFX webView class. With version 1.0.0 the context menu is not opened in JavaFX - 1.0.0 is showing the context menu. In a browser like Chrome the context menu is shown. 
I tried this code
``` javascript
document.addEventListener('contextmenu', function(e) {
        console.log("You've tried to open context menu"); 
        e.preventDefault();
    }, false);
```
and the logout is written. I assume you changed some event handling in version 1.0.1 which causes the above error. 

-- Tolotos

**Comment by jonataswalker** [comment]
@tolotos-rgu May you separate this **JavaFX webView** issue into a new one? So we can deal with it in its particularities.

Thanks.

**Comment by jonataswalker** [comment]
Hey @tolotos-rgu, where have you been? :)

I guess this can be closed, several features mentioned here are now available.

**Comment by tolotos-rgu** [comment]
Thank you - I'm currently bussy with other projects but I try your new version asap.
