### ISSUE TITLE
Pointermove event on contextmenu

### ISSUE THREAD

**Issue by michalmich** [jonataswalker/ol3-contextmenu#102]
Hello,
i`m using your extension and i have problem with registered event map.on('pointermove',...).
In ctxmenu i have two actions wchich add/remove event to/from my map. 

Below is a snippet of my code:

var wlaczDym = function(obj){
			map.on('pointermove', DymekMapa);
			};
var ctxwlaczDym = {
			  text: 'Dymek - on',
			  callback: wlaczDym
			};
var wylaczDym = function(obj){
			map.un('pointermove',DymekMapa);
			};
var ctxwyaczDym = {
		text: 'Dymek - off',
 	        callback: wylaczDym
			};
var contextmenu = new ContextMenu({
			  width: 170,
			  defaultItems: true, 
			  items: [
			    	ctxwlaczDym,
			    	ctxwyaczDym,
			    '-' 
			  ]
			});
map.addControl(contextmenu);
	
The problem is when wlaczDym is active (pointermove is active) and i'm moving cursor on contextmenu then event is still active.  I need to grab features at cursor and then, when i move cursor over contextmenu   pointermove event schould not be active (after pressing button in contextmenu i want write results in another variable to process them). 
Is there any way to disable this behaviour?? 

Best regards.

**Comment by jonataswalker** [comment]
Please provide a fiddle with your code or at least indent it.

**Comment by michalmich** [comment]
Here is jsFiddle project: https://jsfiddle.net/michal_mi/k7qLqjqL/50/
Please try to turn on/off  pointermove event via contextmenu (dymek on, dymek off).
Best regards

**Comment by michalmich** [comment]
Hello,
Have you checked the project, prepared by me?
I like the ability to turn off pointermove event in the context menu. The alternative is to turn off the event on a specific key on the keyboard. Currently, I use the second solution, but it's better to use commands from the context menu. Can you tell me where I'm doing wrong?

**Comment by jonataswalker** [comment]
Hey @michalmich,

I did but I confess that I don't understand what is your problem. What's going wrong with this plugin?

**Comment by michalmich** [comment]
Steps.
1. Turn on dymek in contextmenu -> pointermove event is active and you can see object properties in white div on the map. When you move cursor over the white div (pointer move is not acitve) -> div has class " ol-unselectable" -> when cursor is behind div event pointermove is active.
2. Place cursor near border between green and red polygons ->LPM and contextmenu appears -> place cursor over contextmenu div and move inside contextmenu over green and red polygon -> text in white div changes -> and this is the problem because action "dymek off" schould freeze text in the white div on the map. When i`m over the CTXmenu div the "pointermove event" is still active and he schould`t. With this behavoiur you can`t "freeze" information about object for example for point objects. 
I checked class for div in CTXMenu and he has the same class as the white div on the map.
 
I hope it will help you to understand my problem.
Best regards

**Comment by jonataswalker** [comment]
Ok, @michalmich now I get it. I'll provide a solution. Hold on.

**Comment by jonataswalker** [comment]
Does this solve your issue?

```javascript
// this inside DymekMapa()
if (e.dragging || contextmenu.isOpened()) return;
// I will change this isOpened to isOpen to fix the english grammar
```

**Comment by michalmich** [comment]
Thank you very much. That`s it.:).
Below is fiddle with changes 
https://jsfiddle.net/k7qLqjqL/55/
Best regards

**Comment by jonataswalker** [comment]
You're welcome! Closing. Have a blessed weekend.
