### ISSUE TITLE
mutating the [[Prototype]] of an object

### ISSUE THREAD

**Issue by platonien** [jonataswalker/ol3-contextmenu#105]
Hello, 

I have this warning in my FF debug console. 

**mutating the [[Prototype]] of an object will cause your code to run very slowly; instead create the object with the correct initial [[Prototype]] value using Object.create**

I know that it's just a warning but it maybe make bad performance for application. 
The warning dont appear in Chrome.

Firefox version : 45.7.0 ESR 
Openlayers version : 3.18.2
ol3-contextmenu version : 2.4.0

Thanks for your help :)

**Comment by jonataswalker** [comment]
Hi @platonien, no warning here ... Firefox 51.0.1 - linux.
