### ISSUE TITLE
ol4 compatibility?

### ISSUE THREAD

**Issue by matbeard** [jonataswalker/ol3-contextmenu#107]
I'm using the latest version of OpenLayers (4.0.1) and with the default context menu items (just zoom in/out), I get the following error when clicking either option:
`Uncaught TypeError: Cannot read property 'pan' of undefined`

I just wondered if this was something I'm doing wrong, or if this isn't compatible with ol4.

**Comment by jonataswalker** [comment]
Oh, I'll investigate, hang tight.
