### ISSUE TITLE
Set hitTolerance for right-click 

### ISSUE THREAD

**Issue by matbeard** [jonataswalker/ol3-contextmenu#112]
I'm only showing the context menu if a feature exists, but some of my features are pretty small (< 5 pixles), so it's not easy to get a 'hit'

Is there any way to incorporate a hitTolerance on the event, maybe as a configurable option?

Thanks

**Comment by jonataswalker** [comment]
This is done passing `hitTolerance` to `forEachFeatureAtPixel`.

See https://jsfiddle.net/jonataswalker/3f6g0kho/
