### ISSUE TITLE
great job

### ISSUE THREAD

**Issue by beyondlh** [jonataswalker/ol3-contextmenu#16]
hi,ol3-contextmenu is good,thangs for your work.but it can not create second level menu，like File->Open。if it can create second level menu or more,it will be more great.

**Comment by jonataswalker** [comment]
Hi! This is already in my plans. Keep an eye on it.

**Comment by beyondlh** [comment]
Hi! Thanks for you response。Do you hava a schedule on the submenu?

**Comment by jonataswalker** [comment]
I'm terrible busy trying to release a project of my own, so I can't tell right now about schedule. But I'll dedicate some time as soon as possible.

Have a good day.

**Comment by jonataswalker** [comment]
@beyondlh I guess it's ready now, please take a look at #19.
