### ISSUE TITLE
define icon size via js

### ISSUE THREAD

**Issue by michaelletzgus** [jonataswalker/ol3-contextmenu#17]
I like your ol3-contextmenu, it's looking very good an is easy to use.

Maybe you can add a little feature in the next release:
An option (iconsize) to scale-down (or up) the icon.
This would allow to override the default CSS-value and dynamically change icon sizes from js.

In html.js it should be something like this:

```javascript
if(item.icon){
	item.classname += ' ol-contextmenu-icon';
	style = ' style="background-image:url(' + item.icon + ');';

	if(item.iconsize){
		style += 'background-size:' + item.iconsize + ';';
	} else {
		style+='"'
	}
```

Best regards
 Michael

**Comment by jonataswalker** [comment]
I'm glad you like it, @michaelletzgus.

I'll dedicate some time soon to this plugin.

Have a good day.

**Comment by jonataswalker** [comment]
@michaelletzgus Sorry this delay but are you referring to [this line](https://github.com/jonataswalker/ol3-contextmenu/blob/master/src/ol3-contextmenu.css#L68)? If so, the icon size is scaled automatically by browser.

**Comment by michaelletzgus** [comment]
Hi.
No, I tried to have different icons sizes per menu line, this won't work with one static css  background-size. But now I rearranged my app and scaled my icons properly - so this feature is not needed an more.

**Comment by jonataswalker** [comment]
All right, closing then.
