### ISSUE TITLE
Enable Context Menu only on geometries

### ISSUE THREAD

**Issue by studentitm** [jonataswalker/ol3-contextmenu#20]
The context menu plugin is a great utility.
But the contextmenu opens on right click of every element.
Could you please provide a way by which it opens only on right click of drawn geometries like polygon,circle etc.

**Comment by jonataswalker** [comment]
@studentitm this is a good feature to implement. I'll add it as soon as possible.

**Comment by studentitm** [comment]
Thanks!

**Comment by jonataswalker** [comment]
@studentitm Here's what I've done:

There is now two new methods: `disable` and `enable` and a new event `beforeopen`. So it's up to you, for instance:

```javascript
contextmenu.on('beforeopen', function(evt){
  var feature = map.forEachFeatureAtPixel(evt.pixel, function(ft, l){
    return ft;
  });

  if (feature) { // open only on features
    contextmenu.disable();
  } else {
    contextmenu.enable();
  }
});
```

**Comment by studentitm** [comment]
@jonataswalker  Thanks a lot for this addition!!
It really helped.
Can I also pass parameters to the callback function which has been defined for a particular option in the context menu? At present, the callback function takes an implicit object that has coordinates of the clicked position and a data key.
I want to take some information from the right clicked feature and pass it to the callback function.
Right now, I am clearing the contextmenu on right click, add data to option and then push it in the contextmenu.
Can I somehow set the value of this data key dynamically,when the target feature is right clicked?

**Comment by jonataswalker** [comment]
Moved your question to another ticket ( #33  ), ok? @studentitm
