### ISSUE TITLE
Dismiss contextmenu outside of map

### ISSUE THREAD

**Issue by vikash159** [jonataswalker/ol3-contextmenu#35]
Im unable to dismiss context menu outside of map, how i can dismiss, there is no method to dismiss the popup. tried dispose, but it completely remove the context-menu, setting up again il never shown on map.

**Comment by jonataswalker** [comment]
Did you try `contextmenu.disable()`?

**Comment by jonataswalker** [comment]
See https://github.com/jonataswalker/ol3-contextmenu#if-you-want-to-disable-this-plugin-under-certain-circumstances-listen-to-beforeopen

**Comment by vikash159** [comment]
disable isnt working, i have to dismiss the contextmenu if user clicked outside the map, if i clear the contents the contextmenu container still visible with empty rows.

**Comment by jonataswalker** [comment]
May you please show the code you're trying? Better yet a [JSFiddle](https://jsfiddle.net/).

**Comment by vikash159** [comment]
https://s31.postimg.org/l5l2ni0ob/empty_row.png

its actually look like above image when i use contextmenu.clear();

**Comment by vikash159** [comment]
http://jsfiddle.net/vikash159/ooxs1w5d/18/
i need to manually clear context menu window from map if i clicked outside of map. please review above jsfiddle.

**Comment by vikash159** [comment]
finally i have dismissed the contextmenu manually by this code
contextmenu.container.className = "ol-ctx-menu-container ol-unselectable ol-ctx-menu-hidden";

**Comment by jonataswalker** [comment]
With [v2.2.0](https://github.com/jonataswalker/ol3-contextmenu/releases/tag/2.2.0) you can now use `contextmenu.close()`.

Feel free to reopen this ticket.

**Comment by vikash159** [comment]
Thanks i created exactly the same one..
