### ISSUE TITLE
Uncaught TypeError: e.getTargetElement is not a function

### ISSUE THREAD

**Issue by preeve9534** [jonataswalker/ol3-contextmenu#38]
I have a fresh install of ol3-contextmenu which I am initialising with an empty items array:

this.contextMenu = new ContextMenu({ width: 170, default_items: true, items: [] });
this.map.addControl(this.contextMenu);

The addControl operation generates an uncaught type error:

ol3-contextmenu.js:8 Uncaught TypeError: e.getTargetElement is not a function
    p.setListeners @ ol3-contextmenu.js:8
    p.init @ ol3-contextmenu.js:8e.setMap @ ol3-contextmenu.js:8
    (anonymous function) @ ol.js:518id @ ol.js:33
    k.dispatchEvent @ ol.js:31
    k.Xc @ ol.js:91
...
...

**Comment by jonataswalker** [comment]
Did you close this ticket intentionally? That is, everything is fine with ol3-contextmenu.

**Comment by preeve9534** [comment]
Hi Jonas,

Yes, my bad - old version of ol3.  ol3-contextmenu is very nice ... except
that I now have a positioning issue
posted in another ticket.

Thanks for your work on this.

P

On 29 June 2016 at 12:18, Jonatas Walker <notifications@github.com> wrote:

> Did you close this ticket intentionally? That is, everything is fine with
> ol3-contextmenu.
>
> —
> You are receiving this because you modified the open/close state.
> Reply to this email directly, view it on GitHub
> <https://github.com/jonataswalker/ol3-contextmenu/issues/38#issuecomment-229327895>,
> or mute the thread
> <https://github.com/notifications/unsubscribe/ATQXsfzJL70Nix7EiEpdP3bGSnP6oR25ks5qQlSCgaJpZM4JAS9R>
> .
>



-- 
Paul Reeve

Email: preeve@pdjr.eu
Tel: +44.1469.531428
