### ISSUE TITLE
 TypeError: Cannot read property 'addEventListener' of null

### ISSUE THREAD

**Issue by kumba007** [jonataswalker/ol3-contextmenu#42]
Hi i am getting this error ( Cannot read property 'addEventListener' of null ) While implementing to my maps codes , Could you guid me to resolve this issue please .

Openlayers 3.16 Version i am using 

I am new to here n this domain so please help me solve 

Thanks & Regards 
KuMbA

**Comment by jonataswalker** [comment]
You'll have to show the code you're using. Maybe a jsFiddle?

**Comment by kumba007** [comment]
I have found the issue myself Brother Thanks for the wonderful extension

**Comment by jonataswalker** [comment]
Ahh good to know. Glad you like it.
