### ISSUE TITLE
npm module

### ISSUE THREAD

**Issue by mariomurrent-softwaresolutions** [jonataswalker/ol3-contextmenu#43]
Is it possible that you publish the context menu module on npm?

**Comment by jonataswalker** [comment]
@mariomurrent-softwaresolutions  Would you mind to point how this is useful for you?

**Comment by mariomurrent-softwaresolutions** [comment]
Well it Is easier to manage packages via npm in a nodejs project. E.g.: An AngularJS Project with openlayers 3.

**Comment by jonataswalker** [comment]
@mariomurrent-softwaresolutions  NPM [published](https://www.npmjs.com/package/ol3-contextmenu).
