### ISSUE TITLE
How to pass parameters to a callback function

### ISSUE THREAD

**Issue by kennethhutw** [jonataswalker/ol3-contextmenu#48]
How to pass parameters to a callback function? 

```
function tryMe (param1, param2) {
    alert (param1 + " and " + param2);
}

{
    text: 'Add a Marker',
    icon: 'img/marker.png',
    callback: tryMe (param1, param2)
  }
```

**Comment by jonataswalker** [comment]
Hey @kennethhutw this is not really well explained in README but you can pass a data property in constructor like:

```javascript
function tryMe (obj) {
    alert (obj.param1 + " and " + obj.param2);
}

{
    text: 'Add a Marker',
    icon: 'img/marker.png',
    callback: tryMe,
    data: {
        param1: 'something',
        param2: 'something else'
    }
}
```
And you can pass it on-the-fly like:
```javascript
contextmenu.on('open', function(evt) {
  tryMe.data.param3 = 'some data';
});
```

**Comment by kennethhutw** [comment]
Thank you very much. It is helpful.

**Comment by glchua2** [comment]
Using your fiddle provided [here](http://jsfiddle.net/jonataswalker/ooxs1w5d/), i tried to create a sub menu item and change the callback to be in this sub menu item, however, it seems like it is unable to retrieve information to delete marker. I got the following error message when I click the subMenu item, "Uncaught TypeError: Cannot read property 'marker' of null"

Below is the updated menu item:
`  var secondaryItem = [
  {
  	text: 'removeMarker subMenu',
    callback: removeMarker
  }
  ]; 
  var removeMarkerItem = {
    text: 'Remove this Marker',
    icon: url_marker,
    items: secondaryItem
  };`

Below is the updated contextmenu.on function:
`  contextmenu.on('open', function(evt){
    var feature = map.forEachFeatureAtPixel(evt.pixel, function(ft, l){
      return ft;
    });
    if (feature && feature.get('type') == 'removable') {
      contextmenu.clear();
     secondaryItem.data = {
     		marker:feature
     };
     contextmenu.push(removeMarkerItem);
    } else {
      contextmenu.clear();
      contextmenu.extend(contextmenu_items);
      contextmenu.extend(contextmenu.getDefaultItems());
    }
  });`
