### ISSUE TITLE
How do I open a menu after close a menu

### ISSUE THREAD

**Issue by kennethhutw** [jonataswalker/ol3-contextmenu#50]
I would like to open a menu which keep opening after closing a menu. 

I open a menu and the select a item. After that, I would like to show another menu which has "save" and "Cancel" option. However, the second just show up for a while. 

![untitled_screencast_6_](https://cloud.githubusercontent.com/assets/11795929/17619610/19ad6ab8-60b9-11e6-960a-d0cbb118fd9b.gif)

**Comment by jonataswalker** [comment]
Right, I'll see what's happening but what about a submenu?

**Comment by kennethhutw** [comment]
Can you look at my code -- []( https://plnkr.co/edit/NgIpC3?p=info)
Step 1. right click -> Draw -> Polygon 
        2. draw a polygon and then double-click
        3. enter a title name 
        4. right click on polygon --> Edit Area
       
After click edit Area option, It should show a context menu (Cancel, Save) but it just show 

![untitled_screencast_1_](https://cloud.githubusercontent.com/assets/11795929/17689910/a13e7182-63bd-11e6-9b33-b8c7bfe85138.gif)


`

function handleFeatureContexMenuEvent2(option, ID, ModelName, x, y) {
    contextmenu.clear();
    if (option == 'edit') {
       console.log('edit');
    } else if (option == 'view') {
         console.log('view');
    } else if (option == 'editarea') {
        console.log('editarea');
        var AreaEditMenu = [
            {
                text: 'Save', 
            },
            {
                text: 'Cancel',
            }
        ];
        contextmenu.extend(AreaEditMenu);
    }
}
`

**Comment by jonataswalker** [comment]
A workaround would be a submenu (Save, Cancel) to _EditArea_ item.

I've forked [your plunker to show it](https://plnkr.co/edit/UNt6fG?p=preview), and I've made some changes, specially changing:

```javascript
map.getViewport().addEventListener('contextmenu', function (e) {
    e.preventDefault();
    var offset = $(this).offset();
    var mapX = e.x - offset.left;
    var mapY = e.y - offset.top;
    var clkfeatures = [];
    map.forEachFeatureAtPixel([mapX, mapY], function (ft, layer) {
        if(typeof ft.get('ModelName') !== 'undefined'){
              if (!contains.call(clkfeatures, ft)){
                  clkfeatures.push(ft);
              }
        }
    });
    
    // ....
});
```
To:

```javascript
contextmenu.on('open', function(evt) {
    var clkfeatures = [];
    map.forEachFeatureAtPixel(evt.pixel, function (ft, layer) {
        if(typeof ft.get('ModelName') !== 'undefined'){
            if (!contains.call(clkfeatures, ft)){
                clkfeatures.push(ft);
            }
        }
    });

    // ...
});
```

Because _ol3-contextmenu_ is already listening `contextmenu` for you.

**Comment by kennethhutw** [comment]
Hello jonataswalker

Thank you very much but it is not what I want.  I hope that user should select edit area option and then modify features. the last step is only to choice save or cancel option. So when modifying  feature, user only can see the save and cancel options on menu so I hope Menu can stick on map when user are modifying the feature.

May I know why ContextMenu don't has Open Method? 

If it cannot be done, that's okay.  I will change my workflow. 

Thank you for your help again

**Comment by jonataswalker** [comment]
> May I know why ContextMenu don't has Open Method?

It is a bit complicated and as it is pretty simple you trigger a right click on your own, I'll let it with you:

```javascript
    var contextMenuEvent = new CustomEvent('contextmenu', {
      bubbles: true,
      cancelable: true
    });
    contextMenuEvent.clientX = contextMenuEvent.pageX = 100; // set pixel coordinate
    contextMenuEvent.clientY = contextMenuEvent.pageY = 100;

    map.getTargetElement().dispatchEvent(contextMenuEvent);
```

**Comment by kennethhutw** [comment]
Ok, thank you very much for your help.
