### ISSUE TITLE
Make the event triggering the open menu action configurable.

### ISSUE THREAD

**Issue by ZancaM** [jonataswalker/ol3-contextmenu#54]
For example change the opening of the  context menu on single left (regular) click.

**Comment by ZancaM** [comment]
For now I tweaked the library myself for my purpose:
https://github.com/jonataswalker/ol3-contextmenu/blob/master/src/js/internal.js#L158
I changed contextmenu to click to enable the menu on single click.
Ideally this could be coming as a property when we create the object 
new ContextMenu({
   'event':'click',
   ...
})

**Comment by jonataswalker** [comment]
@ZancaM I'm glad you reached a solution but I'm not sure about this. It looks like, for me, a bit intrusive.

Maybe you have some more arguments? Or others?

**Comment by jonataswalker** [comment]
With #73 you can set the event type.
