### ISSUE TITLE
BUG: remove ContextMenu from Controls collection

### ISSUE THREAD

**Issue by ollazarev** [jonataswalker/ol3-contextmenu#55]
Bug on 40 line: http://jsfiddle.net/gLmq75sp/1/

map.removeControl(contextmenu) calls Base.setMap(null) function, which results in an error

**Comment by jonataswalker** [comment]
Thanks for reporting @ollazarev.

Let me see how to fix it.

**Comment by jonataswalker** [comment]
@ollazarev please see #57.

**Comment by ollazarev** [comment]
@jonataswalker thanks. It's work
