### ISSUE TITLE
is ctxmenu visible?

### ISSUE THREAD

**Issue by michaelletzgus** [jonataswalker/ol3-contextmenu#56]
Hi,

Is it possible to determine if the context menu is currently be displayed or not?
Some kind of .isVisible() function?

Best regards
 Michael

**Comment by jonataswalker** [comment]
Hi @michaelletzgus how would be this? Would you like to know if the menu is opened?

**Comment by michaelletzgus** [comment]
Yes, I want to know if the menu is opened.

**Comment by jonataswalker** [comment]
Sorry @michaelletzgus this delay but I'm going to provide a solution as soon as possible.

**Comment by jonataswalker** [comment]
Added in #74
