### ISSUE TITLE
Submenu "leaves" the ol3 map

### ISSUE THREAD

**Issue by YoannBureau** [jonataswalker/ol3-contextmenu#70]
Hi Jonatas,

I'm using your component with sub menus. I have around 10 elements in the sub menu, and when it right click at the "bottom" of the page, the sub menu will partially disapear:

I illustrated it in a image:
http://nsa38.casimages.com/img/2016/09/29/160929120456152917.png

Here is a quick JS Fiddle that reproduces the bug: http://jsfiddle.net/YoannBureau/ooxs1w5d/44/

Thanks a lot!

**Comment by jonataswalker** [comment]
Ah yes, I mean that's horrible. I'm not computing the left space for the submenu.

I'll provide a solution ASAP. @YoannBureau thank you for reporting this bug.

**Comment by jonataswalker** [comment]
@YoannBureau feel free to come up with a solution if you have some time.
