### ISSUE TITLE
unable to pass parameter to a callback function in sub-menu item

### ISSUE THREAD

**Issue by glchua2** [jonataswalker/ol3-contextmenu#79]
Using your fiddle provided [here](http://jsfiddle.net/jonataswalker/ooxs1w5d/), i tried to create a sub menu item and change the callback to be in this sub menu item, however, it seems like it is unable to retrieve information to delete marker. I got the following error message when I click the subMenu item, "Uncaught TypeError: Cannot read property 'marker' of null"

Below is the updated menu item:
`  var secondaryItem = [
  {
  	text: 'removeMarker subMenu',
    callback: removeMarker
  }
  ]; 
  var removeMarkerItem = {
    text: 'Remove this Marker',
    icon: url_marker,
    items: secondaryItem
  };`

Below is the updated contextmenu.on function:
`  contextmenu.on('open', function(evt){
    var feature = map.forEachFeatureAtPixel(evt.pixel, function(ft, l){
      return ft;
    });
    if (feature && feature.get('type') == 'removable') {
      contextmenu.clear();
     secondaryItem.data = {
     		marker:feature
     };
     contextmenu.push(removeMarkerItem);
    } else {
      contextmenu.clear();
      contextmenu.extend(contextmenu_items);
      contextmenu.extend(contextmenu.getDefaultItems());
    }
  });`

**Comment by jonataswalker** [comment]
Hey @glchua2!

Are you able to create a fiddle with your code?

**Comment by glchua2** [comment]
Please take a look at this [fiddle](http://jsfiddle.net/ooxs1w5d/52/).

**Comment by jonataswalker** [comment]
You should pass `data` like this:
```javascript
secondaryItem[0].data = {
  marker: feature
};
```
`data` must be a property of a specific (sub) item.

**Comment by glchua2** [comment]
I understand that [0] allow for pointing to a specific sub item and also because i declared it as an array. So if i want to set for second item in the sub menu i assume i have to use [1].

Maybe include more examples to cover cases such as this so that it will be easier to understand.
