### ISSUE TITLE
Changing the entries in a context menu while it is displayed can cause it to not fit on the screen

### ISSUE THREAD

**Issue by Saurbaum** [jonataswalker/ol3-contextmenu#80]
I'm attempting to use this menu to display a note to the user when they right click on a feature so that I can let them know something is happening while I make requests to get the data specific to the feature they have clicked on.

When I have the entries I want to display I update the menu.

Everything works fine until there are too many entries and the menu goes off the bottom of the page.

I tried updating to v2.3.0 but it didn't help.

**Comment by jonataswalker** [comment]
@Saurbaum 

Off the top of my head I don't see a workaround for this.

Maybe if we have a `updatePosition()` method. Are you able to provide a PR?

**Comment by Saurbaum** [comment]
I was getting set to submit something to fix this and did a last minute fetch of the latest and turns out it's already working.

**Comment by Saurbaum** [comment]
And this is why developing on only a few hours is a bad plan.

It is a problem if the menu is loaded in such a way that it wouldn't over flow with minimal entries and then the new ones would cause it to grow too large.  If then menu would over flow with a single entry then the new ones will be added causing it to grow upwards.

I'll get back to trying to find a solution and submit a pull request.

**Comment by Saurbaum** [comment]
I've forked and updated the source files.  I don't think I'm setup for building the minified versions but I'll submit the pull request and see what I've done wrong.

**Comment by jonataswalker** [comment]
@Saurbaum Thanks for working on this PR #81. I've made some reviews there.

**Comment by Saurbaum** [comment]
Thanks for letting the change in.  Any chance you can push a new build live?

**Comment by jonataswalker** [comment]
I was thinking about submit some other changes before a new release. Are you in a hurry for this new method?

**Comment by Saurbaum** [comment]
Sometime in the next 2 weeks would be good for me so I can push it live with my next update.
