### ISSUE TITLE
Multiple maps

### ISSUE THREAD

**Issue by drewgilliam** [jonataswalker/ol3-contextmenu#83]
Hi!  Great stuff, but I have a new use case that isn't working as expected. 

I have two side-by-side maps, each map needing an independent context menu.  Unfortunately, clearing, pushing, or extending the first context menu will unexpectedly affect the second context menu.  

[JSFIDDLE](https://jsfiddle.net/drewgilliam/jqsra2az/)

- Right click in the bottom map to view the context menu

- Right click in the upper map to view the context menu

- Items unexpectedly appear in the bottom context menu during upper map right click

It seems as though much of the code ends up referencing only the last context menu you create.  I did notice the "li" element IDs were not unique in the case of multiple context menus, but correcting that issue wasn't enough to solve the problem. 

Any ideas? Thanks in advance for any help!

**Comment by jonataswalker** [comment]
Hey @drewgilliam,

Fixed with PR #84. Thank you for reporting this bug.
