### ISSUE TITLE
Context menu doesn't close when using mouse wheel.

### ISSUE THREAD

**Issue by Saurbaum** [jonataswalker/ol3-contextmenu#87]
If you right click on a map then use the mouse wheel to zoom the map then the context menu remains on screen.

This means it's possible for the menu to be displayed in an area that it is not relevant for when clicking on a menu option.  I believe I can work around this in my own code but it seems like something the context menu itself should also account for.

**Comment by jonataswalker** [comment]
Well, I'm not sure since this can be handled on app side. At first sight it seems a bit intrusive.

**Comment by jonataswalker** [comment]
Closing for now.
