### ISSUE TITLE
method close() has stop working since 2.3 release

### ISSUE THREAD

**Issue by rsobies** [jonataswalker/ol3-contextmenu#90]
if you change ol3-contextmenu from 2.2.4 to 2.3+ method close() stops working.
tested on javafx webview
`
var onOpenMenu = function (evt) {

      ..
            contextMenu.close();
.
      
    };

    contextMenu.on('open', onOpenMenu);
`

empty menu is still visible on map

**Comment by jonataswalker** [comment]
I know nothing about javafx webview but everything is working fine here.
