### ISSUE TITLE
width: 'auto'

### ISSUE THREAD

**Issue by rsobies** [jonataswalker/ol3-contextmenu#96]
it would be nice if menu(and submenu) was auto trim. now if i set width: 'auto' sub menu items are displayed on the main menu. the main menu is ok.

**Comment by jonataswalker** [comment]
Would you mind to put this on a fiddle?

**Comment by rsobies** [comment]
you mean to leave over? no i don't

**Comment by jonataswalker** [comment]
No, I meant put your code on a [jsFiddle](https://jsfiddle.net/) so I can see what's going on.

**Comment by rsobies** [comment]
no, go ahead

**Comment by rsobies** [comment]
i hope the link is working http://jsfiddle.net/fmbtpw3u/

added one sub menu

**Comment by jonataswalker** [comment]
I can't find an easy solution for this issue. What would be the benefit of `auto` width instead of a fixed width?

**Comment by rsobies** [comment]
the text in menu can change every time it is displayed so flexible witdth is ok.
when menu width is fixed, text is wrapped

**Comment by jonataswalker** [comment]
@rsobies I've tried some options and couldn't find a solution for `auto` width. Closing for now.
