### ISSUE TITLE
Default Context Menu

### ISSUE THREAD

**Issue by mckrti** [jonataswalker/ol3-contextmenu#99]
Maybe I missed something, but does the js include a snippet to prevent the default context menu from opening?

Right now I added 

    $('body').attr('oncontextmenu','return false;');

But I rather not add this if possible.  However unless I have the above, the default context menu for the browser opens.

**Comment by jonataswalker** [comment]
The library prevents default contextmenu:

https://github.com/jonataswalker/ol3-contextmenu/blob/master/src/js/internal.js#L193

Is this happening with this [fiddle](http://jsfiddle.net/jonataswalker/ooxs1w5d/)?

**Comment by mckrti** [comment]
No it is not.  However, I am including the available files here:

    <link href="https://unpkg.com/ol3-contextmenu/build/ol3-contextmenu.min.css" rel="stylesheet">
    <script src="https://unpkg.com/ol3-contextmenu/build/ol3-contextmenu.js"></script>

And my code follows the example:

    initializeContentMenu() {
		var feature, restore;
		var contextmenu = new ContextMenu({
			width: 170,
			defaultItems: true
			});
		map.addControl(_this.contextmenu);
		var addFeatureCallback = function(obj) {
			if (obj.data.feature != undefined) {
				var featureId = obj.data.feature.getId();
				var featureIdFixed = featureId.split('_');
				var shape = $('#' + featureIdFixed[0] + '-row').data('shape');
				$("input[name='feature-selector-button']").prop('checked',false);
				$("input[name='feature-selector-button']").checkboxradio('refresh');
				$("input[name='feature-manipulation-button']").prop('checked',false);
				$("input[name='feature-manipulation-button']").checkboxradio('refresh');
				functionD(featureIdFixed[0], shape);
			}
		}
		var editFeatureCallback = function(obj) {
			if (obj.data.feature != undefined) {
				var featureId = obj.data.feature.getId();
				var featureIdFixed = featureId.split('_');
				functionX(featureIdFixed[0]);
			}
		}
		var removeFeatureCallback = function(obj) {
			if (obj.data.feature != undefined) {
				var featureId = obj.data.feature.getId();
				var featureIdFixed = featureId.split('_');
                if ($("#" + featureIdFixed[0] + "-row").data('annotator') == _this.userName) {
					var r = confirm("Are you sure you want to remove the feature?");
                    if (r == true) {
                        functionR(featureIdFixed[0]);
                    }
                } else {
                    alert("Error.");
                }
			}
		}
		var addFeatureItem = {
			text: 'Add Feature Instance',
			callback: addFeatureCallback
		};
		var editFeatureItem = {
			text: 'Edit Feature Instance',
			callback: editFeatureCallback
		};
		var removeFeatureItem = {
			text: 'Remove Feature Instance',
			callback: removeFeatureCallback
		};
		var restore = false;
		contextmenu.on('open', function(evt){
			feature = .map.forEachFeatureAtPixel(evt.pixel, function(ft, l){
				return ft;
			});
			if (feature) {
				contextmenu.clear();
				addFeatureItem.data = {
					feature: feature
				};
				editFeatureItem.data = {
					feature: feature
				};
				removeFeatureItem.data = {
					feature: feature
				};
				contextmenu.push(addFeatureItem);
				contextmenu.push(editFeatureItem);
				contextmenu.push(removeFeatureItem);
				restore = true;
			} else if (restore) {
				contextmenu.clear();
				contextmenu.extend(contextmenu_items);
				contextmenu.extend(_this.contextmenu.getDefaultItems());
				restore = false;
			}
		});
	}

**Comment by jonataswalker** [comment]
@mckrti Is this still a valid issue? Closing for now.
